'use strict';

const fs = require('fs');
const path = require('path');
const { generateAgentsMd } = require('./generate-agents-md');
const { generateAllCommands } = require('./generate-commands');
const { injectAgentSkills } = require('./inject-agent-skills');
const { AGENT_NAMES, ENTERPRISE_AGENT_NAMES } = require('./constants');

const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');
const GTD_DIR = path.join(__dirname, '..', 'get-things-done');

/**
 * Install RapidX for Codex CLI/App.
 */
function installCodex(options) {
  const { targetDir, profile, stack, components } = options;

  const codexDir = path.join(targetDir, '.codex');
  const agentsSkillsDir = path.join(targetDir, '.agents', 'skills');
  const agentsAgentsDir = path.join(targetDir, '.agents', 'agents');
  const commandsDir = path.join(codexDir, 'commands', 'rapidx');
  fs.mkdirSync(codexDir, { recursive: true });
  fs.mkdirSync(agentsSkillsDir, { recursive: true });
  fs.mkdirSync(agentsAgentsDir, { recursive: true });
  fs.mkdirSync(commandsDir, { recursive: true });

  const fe = stack.frontend || {};
  const be = stack.backend || {};
  const db = stack.database || {};
  const profileId = profile.profile_id || 'default';

  // Generate .codex/config.toml
  const configToml = `# RapidX Codex Configuration
# Generated by RapidX Agentic Engineering Platform

[profile]
id = "${profileId}"
client = "${profile.client_name || 'RapidX Project'}"
maturity = "${(profile.engagement && profile.engagement.maturity_level) || 'L1'}"

[stack]
frontend = "${fe.framework || ''}"
frontend_version = "${fe.version || ''}"
backend_language = "${be.language || ''}"
backend_version = "${be.language_version || ''}"
backend_framework = "${be.framework || ''}"
database = "${db.primary || ''}"
database_version = "${db.primary_version || ''}"

[components]
rules = [${components ? Array.from(components.rules).map(r => `"${r}"`).join(', ') : ''}]
skills = [${components ? Array.from(components.skills).map(s => `"${s}"`).join(', ') : ''}]
agents = [${components ? Array.from(components.agents).map(a => `"${a}"`).join(', ') : ''}]

[workflow]
engine = "get-things-done"
commands_dir = ".codex/commands/rapidx"
`;

  fs.writeFileSync(path.join(codexDir, 'config.toml'), configToml, 'utf8');

  // Generate .codex/AGENTS.md
  const agentsMd = generateAgentsMd(profile, stack, components);
  fs.writeFileSync(path.join(codexDir, 'AGENTS.md'), agentsMd, 'utf8');

  // Copy selected skills to .agents/skills/
  const skills = components ? Array.from(components.skills) : [];
  for (const skill of skills) {
    const skillSrc = path.join(TEMPLATES_DIR, 'skills', skill, 'SKILL.md');
    const destPath = path.join(agentsSkillsDir, `${skill}.md`);
    if (fs.existsSync(skillSrc)) {
      fs.copyFileSync(skillSrc, destPath);
    } else {
      fs.writeFileSync(destPath, `# Skill: ${skill}\n\nSee full skill documentation.\n`, 'utf8');
    }
  }

  // Install agent definition files to .agents/agents/
  const requestedAgents = components ? Array.from(components.agents) : AGENT_NAMES;
  const installedSkills = components ? components.skills : new Set();
  let agentCount = 0;

  for (const agentName of requestedAgents.filter(a => AGENT_NAMES.includes(a))) {
    const srcFile = path.join(TEMPLATES_DIR, 'agents', `${agentName}.md`);
    if (!fs.existsSync(srcFile)) continue;
    const raw = fs.readFileSync(srcFile, 'utf8');
    const augmented = injectAgentSkills(raw, agentName, installedSkills, 'codex');
    fs.writeFileSync(path.join(agentsAgentsDir, `rapidx-${agentName}.md`), augmented, 'utf8');
    agentCount++;
  }

  for (const agentName of requestedAgents.filter(a => ENTERPRISE_AGENT_NAMES.includes(a))) {
    const srcFile = path.join(TEMPLATES_DIR, 'agents', 'rapidx', `${agentName}.md`);
    if (!fs.existsSync(srcFile)) continue;
    const raw = fs.readFileSync(srcFile, 'utf8');
    const augmented = injectAgentSkills(raw, agentName, installedSkills, 'codex');
    fs.writeFileSync(path.join(agentsAgentsDir, `rapidx-${agentName}.md`), augmented, 'utf8');
    agentCount++;
  }

  if (agentCount > 0) {
    process.stdout.write(`  [RapidX] Installed ${agentCount} agent definitions → .agents/agents/\n`);
  }

  // Generate RapidX command files in .codex/commands/rapidx/
  const gtdSrc = path.join(GTD_DIR, 'commands', 'gtd');
  const gtdResult = generateAllCommands(gtdSrc, { cursor: commandsDir }, { gtdDir: GTD_DIR });
  if (gtdResult.generated > 0) {
    process.stdout.write(`  [RapidX] Generated ${gtdResult.generated} RapidX commands → .codex/commands/rapidx/\n`);
  }

  // Generate RapidX enterprise command files
  const rapidxSrc = path.join(TEMPLATES_DIR, 'commands', 'rapidx');
  if (fs.existsSync(rapidxSrc)) {
    const rapidxResult = generateAllCommands(rapidxSrc, { cursor: commandsDir }, { gtdDir: GTD_DIR, nativeSource: true });
    if (rapidxResult.generated > 0) {
      process.stdout.write(`  [RapidX] Generated ${rapidxResult.generated} RapidX enterprise commands → .codex/commands/rapidx/\n`);
    }
  }

  return { success: true };
}

module.exports = { installCodex };
