'use strict';

const fs = require('fs');
const path = require('path');
const { generateAgentsMd } = require('./generate-agents-md');

const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

/**
 * Install RapidX for Codex CLI/App.
 */
function installCodex(options) {
  const { targetDir, profile, stack, components } = options;

  const codexDir = path.join(targetDir, '.codex');
  const agentsSkillsDir = path.join(targetDir, '.agents', 'skills');
  fs.mkdirSync(codexDir, { recursive: true });
  fs.mkdirSync(agentsSkillsDir, { recursive: true });

  const fe = stack.frontend || {};
  const be = stack.backend || {};
  const db = stack.database || {};
  const profileId = profile.profile_id || 'default';

  // Generate .codex/config.toml
  const configToml = `# RapidX Codex Configuration
# Generated by RapidX Agentic Engineering Platform

[profile]
id = "${profileId}"
client = "${profile.client_name || 'RapidX Project'}"
maturity = "${(profile.engagement && profile.engagement.maturity_level) || 'L1'}"

[stack]
frontend = "${fe.framework || ''}"
frontend_version = "${fe.version || ''}"
backend_language = "${be.language || ''}"
backend_version = "${be.language_version || ''}"
backend_framework = "${be.framework || ''}"
database = "${db.primary || ''}"
database_version = "${db.primary_version || ''}"

[components]
rules = [${components ? Array.from(components.rules).map(r => `"${r}"`).join(', ') : ''}]
skills = [${components ? Array.from(components.skills).map(s => `"${s}"`).join(', ') : ''}]
agents = [${components ? Array.from(components.agents).map(a => `"${a}"`).join(', ') : ''}]

[workflow]
engine = "get-things-done"
commands_dir = ".claude/commands"
`;

  fs.writeFileSync(path.join(codexDir, 'config.toml'), configToml, 'utf8');

  // Generate .codex/AGENTS.md
  const agentsMd = generateAgentsMd(profile, stack, components);
  fs.writeFileSync(path.join(codexDir, 'AGENTS.md'), agentsMd, 'utf8');

  // Copy selected skills to .agents/skills/
  const skills = components ? Array.from(components.skills) : [];
  for (const skill of skills) {
    const skillSrc = path.join(TEMPLATES_DIR, 'skills', skill, 'SKILL.md');
    const destPath = path.join(agentsSkillsDir, `${skill}.md`);
    if (fs.existsSync(skillSrc)) {
      fs.copyFileSync(skillSrc, destPath);
    } else {
      fs.writeFileSync(destPath, `# Skill: ${skill}\n\nSee full skill documentation.\n`, 'utf8');
    }
  }

  return { success: true };
}

module.exports = { installCodex };
